name: thoga_kade
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.4

dependencies:
  json_annotation: ^4.8.0
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.4.0
  test: ^1.24.0
  mockito: ^5.0.0
  faker: ^2.1.0